// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtykSoEb-UwB8LIQqHarmw1PrCHoZZJ5c',
    appId: '1:750026915544:web:1e9ab63ad1d0252d61a1ad',
    messagingSenderId: '750026915544',
    projectId: 'lifespark-69501',
    authDomain: 'lifespark-69501.firebaseapp.com',
    storageBucket: 'lifespark-69501.appspot.com',
    measurementId: 'G-RLGHYV04BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9hUjUfpEwYD_t-FcZduEl9yIIHcKHEjI',
    appId: '1:750026915544:android:8a471a9e78e76e4c61a1ad',
    messagingSenderId: '750026915544',
    projectId: 'lifespark-69501',
    storageBucket: 'lifespark-69501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMr4nEdqXwym6S9jKzESq-NDkC9PoDlSs',
    appId: '1:750026915544:ios:839dd264c69efe2b61a1ad',
    messagingSenderId: '750026915544',
    projectId: 'lifespark-69501',
    storageBucket: 'lifespark-69501.appspot.com',
    iosBundleId: 'com.example.lifesparkMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMr4nEdqXwym6S9jKzESq-NDkC9PoDlSs',
    appId: '1:750026915544:ios:839dd264c69efe2b61a1ad',
    messagingSenderId: '750026915544',
    projectId: 'lifespark-69501',
    storageBucket: 'lifespark-69501.appspot.com',
    iosBundleId: 'com.example.lifesparkMachineTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtykSoEb-UwB8LIQqHarmw1PrCHoZZJ5c',
    appId: '1:750026915544:web:30e0a1b8d48d9c6661a1ad',
    messagingSenderId: '750026915544',
    projectId: 'lifespark-69501',
    authDomain: 'lifespark-69501.firebaseapp.com',
    storageBucket: 'lifespark-69501.appspot.com',
    measurementId: 'G-ERJ5Q86151',
  );
}
