// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNGf1L8X-Oou4ZBf9c1-02RhBRGWZ3p0o',
    appId: '1:74964081753:web:8f71ef89e9855327b76548',
    messagingSenderId: '74964081753',
    projectId: 'lifespark-2',
    authDomain: 'lifespark-2.firebaseapp.com',
    storageBucket: 'lifespark-2.appspot.com',
    measurementId: 'G-HRPE9MRFCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2gqZMe6KeTVra3pZrBUzrNZDf0z_fmo',
    appId: '1:74964081753:android:acaa96b969bf8a90b76548',
    messagingSenderId: '74964081753',
    projectId: 'lifespark-2',
    storageBucket: 'lifespark-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDou6DFWqJxy1C_5UZ4_UNNSF1CXXFFw4o',
    appId: '1:74964081753:ios:c28f6ad6b01717d7b76548',
    messagingSenderId: '74964081753',
    projectId: 'lifespark-2',
    storageBucket: 'lifespark-2.appspot.com',
    iosBundleId: 'com.example.lifesparkMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDou6DFWqJxy1C_5UZ4_UNNSF1CXXFFw4o',
    appId: '1:74964081753:ios:c28f6ad6b01717d7b76548',
    messagingSenderId: '74964081753',
    projectId: 'lifespark-2',
    storageBucket: 'lifespark-2.appspot.com',
    iosBundleId: 'com.example.lifesparkMachineTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNGf1L8X-Oou4ZBf9c1-02RhBRGWZ3p0o',
    appId: '1:74964081753:web:641c2a38197a8b79b76548',
    messagingSenderId: '74964081753',
    projectId: 'lifespark-2',
    authDomain: 'lifespark-2.firebaseapp.com',
    storageBucket: 'lifespark-2.appspot.com',
    measurementId: 'G-RT3VNBYGWJ',
  );
}
